from .weight_multiple_text import NODE_CLASS_MAPPINGS as WEIGHT_MULTIPLE_TEXT
from .lora_stack_utils import NODE_CLASS_MAPPINGS as LORA_STACK_UTILS
from .simple_timer import NODE_CLASS_MAPPINGS as SIMPLE_TIMER


NODE_CLASS_MAPPINGS = {**WEIGHT_MULTIPLE_TEXT, **LORA_STACK_UTILS, **SIMPLE_TIMER}
NODE_DISPLAY_NAME_MAPPINGS = []
WEB_DIRECTORY = "./js"
__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
